### ISSUE TITLE
Throw an error if a unimplemented method is called

### ISSUE THREAD

**Issue by harnyk** [dariosn85/ts-jest-mocker#3]
I noticed that unimplemented methods return `undefined`, which is not always good, because it is an implicit behavior.

Wouldn't it be better when a method would throw an error with `"not implemented"` message, if it's not implemented?

Example:

```ts
interface Foo {
    bar(): string;
    baz(): number;
}

const foo = mock<Foo>();

// Implementing bar()
foo.bar.mockReturnValue('hello');
// But not implementing baz()

expect(foo.bar()).toBe('hello');

expect(() => foo.baz()).toThrowError('not implemented');
```

**Comment by harnyk** [comment]
Just added a PR fixing it

**Comment by dariosn85** [comment]
@harnyk than you for the contribution. The suggested change makes sense.
