### ISSUE TITLE
Mocked interfaces do not work with `.toEqual()`

### ISSUE THREAD

**Issue by erdnaxeli** [dariosn85/ts-jest-mocker#7]
# Example

```Typescript
interface TestInterface {}

it('test', () => {
    const repo = mock<TestInterface>();
    expect(repo).toEqual(repo);
});
```

# Expected result

It succeeds.

# Actual result

It fails with 

> Error: Method Symbol(Symbol.iterator) is not mocked

# Comment

This is problematic because `.toEqual()` is used by `.toHaveBeenCalledWith()`. This means that if we give a instance of a mocked interface to an object, we can't test that it gives the same instance to something else.

**Comment by dariosn85** [comment]
@erdnaxeli issue resolved in v1.1.0.
